# task
binary_data_dir: './data/binary/'
work_dir: './checkpoints/' # experiment directory. 
infer: false # infer
amp: false
seed: 1234
debug: false
save_codes: ['tasks', 'models', 'modules']

#############
# dataset
#############
ds_workers: 1
endless_ds: true
sort_by_len: true

#########
# train and eval
#########
print_nan_grads: false
load_ckpt: ''
save_best: true
num_ckpt_keep: 100
clip_grad_norm: 0
accumulate_grad_batches: 1
tb_log_interval: 100
num_sanity_val_steps: 5  # steps of validation at the beginning
check_val_every_n_epoch: 10
val_check_interval: 500
ckpt_save_interval: 1000
valid_monitor_key: 'val_loss'
valid_monitor_mode: 'min'
max_epochs: 100000
max_updates: 100000
max_tokens: 20000
max_sentences: 64
eval_max_batches: 128
resume_from_checkpoint: 0
rename_tmux: true