accumulate_grad_batches: 1
amp: false
base_config:
- ./base_task.yaml
- ../datasets/svs/csd/preprocess.yaml
binarization_args:
  dataset_range: index
  max_durations: 8
  min_text: 6
  pos_resolution: 16
  shuffle: true
  tempo_range:
  - 16
  - 256
  test_range:
  - 0
  - 50
  train_range:
  - 100
  - -1
  trim_eos_bos: false
  valid_range:
  - 50
  - 100
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_mel: true
  with_mfa_align: false
  with_midi_align: true
  with_spk_embed: false
  with_spk_f0_norm: false
  with_wav: true
binarizer_cls: preprocessor.base_binarizer.BaseBinarizer
binary_data_dir: ./data/binarize/svs/csd
check_val_every_n_epoch: 10
ckpt_save_interval: 10000
clip_grad_norm: 1
clip_grad_value: 0
debug: false
dec_blocks: '1'
dec_dilation_sizes:
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
dec_kernel_size:
- 3
- 7
- 11
disc_interval: 1
disc_norm: in
disc_reduction: stack
disc_start_steps: 0
disc_win_num: 3
discriminator_optimizer_params:
  eps: 1.0e-09
  weight_decay: 0.0
discriminator_scheduler_params:
  gamma: 0.999875
ds_workers: 8
enc_layers: 6
enc_pre_ln: true
enc_prenet: true
encoder_type: rel_fft
endless_ds: false
eps: 1.0e-09
eval_max_batches: 256
f0_bins: 300
f0_max: 1250
f0_min: 50
f0_resolution: 1
ffn_act: gelu
ffn_filter_channels: 768
ffn_kernel_size: 9
fft_size: 2048
fmax: 12000
fmin: 20
frame_prior_layers: 4
frames_multiple: 1
gen_dir_name: ''
generator_scheduler_params:
  gamma: 0.999875
gin_channels: 256
griffin_lim_iters: 30
hidden_size: 192
hop_size: 300
infer: false
initial_upsample_channels: 512
kl_min: 0.0
kl_start_steps: 1
lambda_ctc: 45.0
lambda_fm: 2.0
lambda_kl: 1.0
lambda_mel_adv: 1.0
lambda_pitch: 10.0
load_ckpt: ''
loud_norm: false
lr: 0.0002
max_epochs: 100000
max_frames: 4096
max_input_tokens: 4000
max_sentences: 64
max_tokens: 60000
max_updates: 1000000
max_valid_sentences: 1
max_valid_tokens: 60000
max_wav_value: 32768.0
mel_disc_hidden_size: 256
mel_losses: l1:45.0
mel_vmax: 1.5
mel_vmin: -6
min_frames: 32
note_range:
- 21
- 128
num_ckpt_keep: 100
num_heads: 2
num_linear_bins: 1025
num_mel_bins: 128
num_sanity_val_steps: 5
num_spk: 1
num_valid_plots: 10
optimizer: AdamW
optimizer_adam_beta1: 0.8
optimizer_adam_beta2: 0.99
out_wav_norm: true
p_dropout: 0.1
phoneme_predictor_layers: 2
pitch_extractor: parselmouth
pitch_key: pitch
pitch_predictor_kernel_size: 9
pitch_predictor_layers: 6
pitch_type: frame
posterior_start_steps: 0
predictor_grad: 0.1
preprocess_args:
  DEFAULT_TEMPO: 120
  add_eos_bos: true
  beat_note_factor: 4
  divided: true
  filter_symbolic: false
  filter_symbolic_ppl: 16
  max_bar: 2
  max_durations: 8
  max_note_dur: 5.0
  max_notes_per_bar: 2
  max_ts_denominator: 6
  melody: true
  melody_num: 0
  mfa_group_shuffle: false
  mfa_offset: 0.02
  min_sil_dur: 8
  nsample_per_mfa_group: 1000
  num_frame: 3
  pos_resolution: 16
  reset_phone_dict: false
  reset_spk_dict: true
  reset_word_dict: true
  save_sil_mask: true
  text_processor: ko_sing
  use_mfa: false
  use_midi: true
  use_text: true
  vad_max_silence_length: 12
  wav_processors:
  - sox_resample
  with_phsep: true
preprocess_cls: config.datasets.svs.csd.preprocess.CSDPreprocessor
print_nan_grads: false
processed_data_dir: ./data/preprocessed/svs/csd
profile_infer: false
raw_data_dir: ./data/source/svs/csd
raw_sample_rate: 48000
rename_tmux: true
resume_from_checkpoint: 0
sample_rate: 24000
save_best: true
save_codes:
- tasks
- models
- modules
save_f0: false
save_gt: true
scheduler: steplr
seed: 1234
segment_size: 32
sort_by_len: true
speaker: csd
task_cls: tasks.visinger.VISingerTask
tb_log_interval: 1000
test_ids: []
test_input_yaml: ''
test_set_name: test
train_set_name: train
train_sets: ''
upsample_kernel_sizes:
- 11
- 11
- 7
- 4
- 4
upsample_rates:
- 5
- 5
- 3
- 2
- 2
use_pesq: true
use_phoneme_pred: true
use_pitch_embed: true
use_pitch_encoder: true
use_pos_embed: true
use_spectral_norm: false
use_spk_embed: false
use_spk_id: true
use_word_input: false
val_check_interval: 5000
valid_infer_interval: 5000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
vocoder: HifiGAN
vocoder_ckpt: ./checkpoints/pretrain
vocoder_config: hifigan
warmup_updates: 4000
weight_decay: 0.001
win_size: 1200
work_dir: svs/visinger
